### PR TITLE
bug : fixed response formatting using rehype and ReactMarkdown

### LINKED ISSUE #62: Copilot Response Formatting Issue
### Problem statement
Copilot's responses are not properly displayed, and there is a lack of formatting in the responses. When you ask a question, the response is displayed as one paragraph, which makes it difficult to read. 

**Expected Behavior:**
Copilot responses should be displayed with proper formatting, making them easily readable and understandable.

Here is a visual of the problem statement
image

### PR DESCRIPTION
**Pull request by VishalPawar1010**
**Description**

This PR fixes #62 

Resolved response formatting issue using rehype and ReactMarkdownlibrary

### CODE REVIEW

**Review by shivay-at-pieces — CHANGES_REQUESTED** [review]
Hi @VishalPawar1010,

Thank you for your contribution! I encountered a type declaration issue when testing the changes locally. To resolve this, please ensure that the necessary type declarations are added. Specifically, you might need to add type declarations for `ReactMarkdown` and `rehypeSanitize`.

**Comment by VishalPawar1010** [comment]
Hello @shivay-at-pieces , I have added specific type declarations for both `ReactMarkdown `and `rehypeSanitize` .
Please let me know for any.

**Review by shivay-at-pieces — CHANGES_REQUESTED** [review]
image


You might have to also take care for formatting the font color of the response, since it doesn't appear well currently in dark mode as seen in this screenshot.

**Comment by VishalPawar1010** [comment]
Hey @shivay-at-pieces , I have added changes in css to resolve in-consistency in font-color of the response.
I hope it works for all the devices.
Please let me know for any.

**Comment by shivay-at-pieces** [comment]
image
Certain parts are not updated properly. I would suggest focus on changing the CSS right now for the Copilot message section

**Comment by VishalPawar1010** [comment]
Yes, I am on it.

**Comment by VishalPawar1010** [comment]
Hey @shivay-at-pieces , I have made required changes to resolve css/font-color conflicts.
Please have a look, It should work fine now.

**Comment by VishalPawar1010** [comment]
In dark mode : 
image

In light mode : 
image

**Comment by mason-at-pieces** [comment]
@shivay-at-pieces we can close the older pr (#102 ) and review this one

**Comment by VishalPawar1010** [comment]
@shivay-at-pieces please let me know, if we need any modifications/corrections for this PR.

Thanks

**Comment by VishalPawar1010** [comment]
Just a heads up-> 
Hey @shivay-at-pieces , @mason-at-pieces : 
If this PR looks good, could please merge it ?
If having any modifications please let me know.
Thanks

**Review by shivay-at-pieces — APPROVED** [review]

**Comment by VishalPawar1010** [comment]
Thank you for the merge.

**Pull request merged**
